program Rad_Test_GUI;

{$R *.res}

uses
  Vcl.Forms,
  System.SysUtils,
  DUnitX.Loggers.XML.NUnit in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.Loggers.XML.NUnit.pas',
  DUnitX.Loggers.GUI.VCL in 'DUnitX.Loggers.GUI.VCL.pas' {GUIVCLTestRunner},
  DUnitX.Linux.Console in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.Linux.Console.pas',
  DUnitX.Assert.Ex in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.Assert.Ex.pas',
  DUnitX.Assert in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.Assert.pas',
  DUnitX.Attributes in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.Attributes.pas',
  DUnitX.AutoDetect.Console in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.AutoDetect.Console.pas',
  DUnitX.Banner in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.Banner.pas',
  DUnitX.CategoryExpression in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.CategoryExpression.pas',
  DUnitX.CommandLine.OptionDef in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.CommandLine.OptionDef.pas',
  DUnitX.CommandLine.Options in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.CommandLine.Options.pas',
  DUnitX.CommandLine.Parser in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.CommandLine.Parser.pas',
  DUnitX.ComparableFormat.Csv in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.ComparableFormat.Csv.pas',
  DUnitX.ComparableFormat in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.ComparableFormat.pas',
  DUnitX.ComparableFormat.Xml in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.ComparableFormat.Xml.pas',
  DUnitX.ConsoleWriter.Base in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.ConsoleWriter.Base.pas',
  DUnitX.Constants in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.Constants.pas',
  DUnitX.DUnitCompatibility in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.DUnitCompatibility.pas',
  DUnitX.Exceptions in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.Exceptions.pas',
  DUnitX.Extensibility in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.Extensibility.pas',
  DUnitX.FilterBuilder in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.FilterBuilder.pas',
  DUnitX.Filters in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.Filters.pas',
  DUnitX.FixtureBuilder in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.FixtureBuilder.pas',
  DUnitX.FixtureProvider in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.FixtureProvider.pas',
  DUnitX.FixtureResult in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.FixtureResult.pas',
  DUnitX.Generics in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.Generics.pas',
  DUnitX.Helpers in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.Helpers.pas',
  DUnitX.Init in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.Init.pas',
  DUnitX.InternalDataProvider in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.InternalDataProvider.pas',
  DUnitX.InternalInterfaces in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.InternalInterfaces.pas',
  DUnitX.Loggers.Null in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.Loggers.Null.pas',
  DUnitX.Loggers.Text in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.Loggers.Text.pas',
  DUnitX.Loggers.XML.xUnit in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.Loggers.XML.xUnit.pas',
  DUnitX.MemoryLeakMonitor.Default in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.MemoryLeakMonitor.Default.pas',
  DUnitX.OptionsDefinition in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.OptionsDefinition.pas',
  DUnitX.ResStrs in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.ResStrs.pas',
  DUnitX.RunResults in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.RunResults.pas',
  DUnitX.ServiceLocator in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.ServiceLocator.pas',
  DUnitX.StackTrace.EurekaLog7 in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.StackTrace.EurekaLog7.pas',
  DUnitX.StackTrace.JCL in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.StackTrace.JCL.pas',
  DUnitX.StackTrace.MadExcept3 in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.StackTrace.MadExcept3.pas',
  DUnitX.StackTrace.MadExcept4 in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.StackTrace.MadExcept4.pas',
  DUnitX.StackTrace.MadExcept5 in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.StackTrace.MadExcept5.pas',
  DUnitX.Test in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.Test.pas',
  DUnitX.TestDataProvider in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.TestDataProvider.pas',
  DUnitX.TestFixture in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.TestFixture.pas',
  DUnitX.TestFramework in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.TestFramework.pas',
  DUnitX.TestNameParser in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.TestNameParser.pas',
  DUnitX.TestResult in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.TestResult.pas',
  DUnitX.TestRunner in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.TestRunner.pas',
  DUnitX.Timeout in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.Timeout.pas',
  DUnitX.Types in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.Types.pas',
  DUnitX.Utils in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.Utils.pas',
  DUnitX.Utils.XML in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.Utils.XML.pas',
  DUnitX.WeakReference in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.WeakReference.pas',
  DUnitX.Windows.Console in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.Windows.Console.pas',
  DUnitX.Loggers.GUI.VCL.RichEdit in '..\..\vendor\VSoftTechnologies\DUnitX\Source\DUnitX.Loggers.GUI.VCL.RichEdit.pas',
  rad.cache.Benchmark.Tests in '..\unit\rad.cache.Benchmark.Tests.pas',
  rad.cache.Tests in '..\unit\rad.cache.Tests.pas',
  rad.cmd.Tests in '..\unit\rad.cmd.Tests.pas',
  rad.eventbus.Benchmark in '..\unit\rad.eventbus.Benchmark.pas',
  rad.eventbus.Tests in '..\unit\rad.eventbus.Tests.pas',
  rad.utils.Tests in '..\unit\rad.utils.Tests.pas',
  help.date.Tests in '..\unit\help.date.Tests.pas',
  rad.thread.Tests in '..\unit\rad.thread.Tests.pas',
  help.str.Tests in '..\unit\help.str.Tests.pas';

begin
  Application.Initialize;
  Application.CreateForm(TGUIVCLTestRunner, GUIVCLTestRunner);
  Application.Run;
end.
