<#
.SYNOPSIS
    Regenerates the tool-specific AI config copies from the single source of
    truth under .agents/, then checks docs/proje-haritasi.md for coverage.

.DESCRIPTION
    This repo keeps ONE canonical copy of its rules and commands under
    .agents/rules and .agents/commands. Claude Code and Cursor each require
    their own physical files (.claude/rules, .cursor/rules, .claude/commands)
    to auto-load them — this script keeps those in sync with the source.

    Skill CONTENT is NOT touched by this script. .agents/skills/*/SKILL.md is
    read natively as a fallback location by Claude Code, Cursor, Codex CLI,
    GitHub Copilot and Gemini/Antigravity CLI (Agent Skills open standard,
    agentskills.io) — no per-tool copies of SKILL.md are needed or created.

    What IS generated per skill: a thin slash-command wrapper at
    .claude/commands/<skill-name>.md. Skills normally trigger from
    natural-language matching against their description, which means a user
    typing e.g. "/some-skill" gets "Unknown command" even though the skill
    itself works fine from a plain-language request. The generated wrapper
    makes every skill ALSO invocable as an explicit "/<skill-name>" command
    that deterministically reads the skill's SKILL.md and follows it from
    its first step — useful when the user wants a guaranteed, predictable
    step-by-step flow instead of relying on trigger-matching. This only
    covers Claude Code (Cursor has no equivalent commands folder yet).

    AGENTS.md, .gemini/rules/project-rules.md and .github/copilot-instructions.md
    are hand-authored summaries that reference .agents/rules for detail — they
    are intentionally NOT generated by this script (see
    .agents/rules/sync-workflow.md for the reasoning).

    After syncing, the script also checks that every file under .agents/rules,
    .agents/commands and .agents/skills is at least MENTIONED BY NAME in
    docs/proje-haritasi.md, and prints a warning list for anything missing.
    This is a coverage check only — it does not (and cannot) write the
    Turkish description itself, since that requires understanding what the
    new rule/skill/command actually does. Whoever adds the file (human or AI)
    must still write that description by hand in the same turn.

.NOTES
    Run this every time a file under .agents/rules/ or .agents/commands/ is
    added, edited or removed, OR a skill is added/removed under
    .agents/skills/. Safe to re-run — stale generated files (deleted from
    source, or from a removed skill) are removed from targets too.
#>

$ErrorActionPreference = 'Stop'

$RepoRoot       = Split-Path -Parent $PSScriptRoot
$AgentsRules    = Join-Path $RepoRoot ".agents/rules"
$AgentsCommands = Join-Path $RepoRoot ".agents/commands"
$AgentsSkills   = Join-Path $RepoRoot ".agents/skills"

$RuleTargets    = @(".claude/rules", ".cursor/rules")
$CommandTargets = @(".claude/commands")
$SkillCommandMarker = "AUTO-GENERATED from .agents/skills"

function Sync-GeneratedDirectory {
    param(
        [Parameter(Mandatory)] [string]$SourceDir,
        [Parameter(Mandatory)] [string]$TargetRelative,
        [Parameter(Mandatory)] [string]$RepoRoot,
        [string]$IgnoreMarker
    )

    $target = Join-Path $RepoRoot $TargetRelative
    if (-not (Test-Path $target)) {
        New-Item -ItemType Directory -Path $target -Force | Out-Null
    }

    $sourceNames = Get-ChildItem -Path $SourceDir -Filter *.md | Select-Object -ExpandProperty Name

    # Copy first, delete stale second: if the script is interrupted between
    # the two steps, the target is left with stale-but-valid files rather
    # than files removed but not yet replaced.
    Get-ChildItem -Path $SourceDir -Filter *.md | ForEach-Object {
        $destination = Join-Path $target $_.Name
        Copy-Item -Path $_.FullName -Destination $destination -Force
        Write-Host "  - synced       : $TargetRelative/$($_.Name)"
    }

    $existingTargetFiles = @(Get-ChildItem -Path $target -Filter *.md -ErrorAction SilentlyContinue)

    # Safety guard: a source that yields zero files while the target already
    # has content almost always means $SourceDir resolved to the wrong path,
    # not that every rule/command was legitimately deleted. Refuse to mass-
    # delete in that case and surface the problem instead of silently wiping
    # the target.
    if ($sourceNames.Count -eq 0 -and $existingTargetFiles.Count -gt 0) {
        throw "Sync-GeneratedDirectory: source '$SourceDir' yielded 0 .md files but target '$TargetRelative' already has $($existingTargetFiles.Count) — refusing to delete. This usually means the source path is wrong, not that every file was legitimately removed. Verify `$SourceDir before re-running."
    }

    $staleFiles = @($existingTargetFiles | Where-Object {
        if ($sourceNames -contains $_.Name) { return $false }
        if ($IgnoreMarker) {
            $fileText = Get-Content -Path $_.FullName -Raw -ErrorAction SilentlyContinue
            if ($fileText -and $fileText.Contains($IgnoreMarker)) { return $false }  # owned by a different generator (e.g. per-skill commands) — leave it alone
        }
        return $true
    })

    if ($staleFiles.Count -gt 0) {
        Write-Host "  - removing $($staleFiles.Count) stale file(s): $($staleFiles.Name -join ', ')"
        $staleFiles | ForEach-Object {
            Remove-Item $_.FullName -Force
            Write-Host "  - removed stale : $TargetRelative/$($_.Name)"
        }
    }
}

Write-Host "Source of truth: .agents/rules, .agents/commands (.agents/skills needs no copying)"
Write-Host ""

Write-Host "Regenerating rules..."
foreach ($t in $RuleTargets) {
    Sync-GeneratedDirectory -SourceDir $AgentsRules -TargetRelative $t -RepoRoot $RepoRoot
}

Write-Host ""
Write-Host "Regenerating commands..."
foreach ($t in $CommandTargets) {
    Sync-GeneratedDirectory -SourceDir $AgentsCommands -TargetRelative $t -RepoRoot $RepoRoot -IgnoreMarker $SkillCommandMarker
}

Write-Host ""
Write-Host "Regenerating skill commands (.claude/commands/<skill-name>.md, one per .agents/skills/*)..."

$SkillCommandTarget = Join-Path $RepoRoot ".claude/commands"
if (-not (Test-Path $SkillCommandTarget)) {
    New-Item -ItemType Directory -Path $SkillCommandTarget -Force | Out-Null
}

$handAuthoredCommandNames = @()
if (Test-Path $AgentsCommands) {
    $handAuthoredCommandNames = Get-ChildItem -Path $AgentsCommands -Filter *.md | Select-Object -ExpandProperty BaseName
}

$generatedSkillNames = New-Object System.Collections.Generic.List[string]

if (Test-Path $AgentsSkills) {
    Get-ChildItem -Path $AgentsSkills -Directory | ForEach-Object {
        $skillName = $_.Name
        $skillMdPath = Join-Path $_.FullName "SKILL.md"

        if ($handAuthoredCommandNames -contains $skillName) {
            Write-Host "  - SKIPPED (name collides with hand-authored .agents/commands/$skillName.md) : $skillName" -ForegroundColor Yellow
            return
        }
        if (-not (Test-Path $skillMdPath)) {
            Write-Host "  - SKIPPED (no SKILL.md found) : $skillName" -ForegroundColor Yellow
            return
        }

        $content = @"
---
description: Directly invoke the $skillName skill, bypassing natural-language trigger matching.
---

<!-- $SkillCommandMarker/$skillName/SKILL.md — do not hand-edit, regenerate via ``pwsh tools/generate-ai-configs.ps1`` -->

Invoke the ``$skillName`` skill now. Read ``.agents/skills/$skillName/SKILL.md`` in full and follow it exactly from its first step — do not skip or reorder steps, and do not silently infer answers to any question it asks; ask them one at a time, in the order the skill defines.
"@
        $destination = Join-Path $SkillCommandTarget "$skillName.md"
        Set-Content -Path $destination -Value $content -Encoding utf8
        $generatedSkillNames.Add($skillName)
        Write-Host "  - generated    : .claude/commands/$skillName.md"
    }
}

Get-ChildItem -Path $SkillCommandTarget -Filter *.md -ErrorAction SilentlyContinue | ForEach-Object {
    $fileText = Get-Content -Path $_.FullName -Raw -ErrorAction SilentlyContinue
    if ($fileText -and $fileText.Contains($SkillCommandMarker)) {
        if (-not $generatedSkillNames.Contains($_.BaseName)) {
            Remove-Item $_.FullName -Force
            Write-Host "  - removed stale : .claude/commands/$($_.Name)"
        }
    }
}

Write-Host ""
Write-Host "Done."

# --- docs/proje-haritasi.md coverage check ------------------------------
$MapFile = Join-Path $RepoRoot "docs/proje-haritasi.md"
if (Test-Path $MapFile) {
    $mapText = Get-Content $MapFile -Raw
    $missing = New-Object System.Collections.Generic.List[string]

    Get-ChildItem -Path $AgentsRules -Filter *.md | ForEach-Object {
        if ($mapText -notmatch [regex]::Escape($_.Name)) {
            $missing.Add(".agents/rules/$($_.Name)")
        }
    }
    Get-ChildItem -Path $AgentsCommands -Filter *.md | ForEach-Object {
        if ($mapText -notmatch [regex]::Escape($_.Name)) {
            $missing.Add(".agents/commands/$($_.Name)")
        }
    }
    $agentsSkills = Join-Path $RepoRoot ".agents/skills"
    if (Test-Path $agentsSkills) {
        Get-ChildItem -Path $agentsSkills -Directory | ForEach-Object {
            if ($mapText -notmatch [regex]::Escape($_.Name)) {
                $missing.Add(".agents/skills/$($_.Name)")
            }
        }
    }

    if ($missing.Count -gt 0) {
        Write-Host ""
        Write-Host "WARNING: docs/proje-haritasi.md does not mention:" -ForegroundColor Yellow
        $missing | ForEach-Object { Write-Host "  - $_" -ForegroundColor Yellow }
        Write-Host "Add a row/description for each before finishing this turn." -ForegroundColor Yellow
    } else {
        Write-Host ""
        Write-Host "docs/proje-haritasi.md coverage: OK (every rule/command/skill is mentioned)."
    }
} else {
    Write-Host ""
    Write-Host "NOTE: docs/proje-haritasi.md not found — skipping coverage check." -ForegroundColor Yellow
}
