<#
.SYNOPSIS
    Regenerates the tool-specific AI config copies from the single source of
    truth under .agents/, then checks docs/proje-haritasi.md for coverage.

.DESCRIPTION
    This repo keeps ONE canonical copy of its rules and commands under
    .agents/rules and .agents/commands. Claude Code and Cursor each require
    their own physical files (.claude/rules, .cursor/rules, .claude/commands)
    to auto-load them — this script keeps those in sync with the source.
    Cursor's copies carry the .mdc extension, which its rules engine requires;
    a plain .md file under .cursor/rules is silently ignored.

    Skill CONTENT is never copied or edited by this script, but skills DO need
    a per-tool entry point. Claude Code discovers skills only from
    .claude/skills/ — .agents/skills/ is not one of its discovery locations,
    so a kit whose skills live only there gets none of them auto-triggered.
    This script therefore creates one junction/symlink per skill under
    .claude/skills/, pointing back at .agents/skills/<name>. Claude Code
    resolves those links and loads each skill exactly once. Editing still
    happens in exactly one place: .agents/skills/.

    (Corrected: an earlier version of this script claimed .agents/skills/ was
    "read natively as a fallback location by Claude Code, Cursor, Codex CLI,
    GitHub Copilot and Gemini/Antigravity CLI". That was never verified and is
    not true of Claude Code; it left every skill in every generated kit
    unreachable by trigger matching.)

    What IS generated per skill: a thin slash-command wrapper at
    .claude/commands/<skill-name>.md. Skills normally trigger from
    natural-language matching against their description, which means a user
    typing e.g. "/some-skill" gets "Unknown command" even though the skill
    itself works fine from a plain-language request. The generated wrapper
    makes every skill ALSO invocable as an explicit "/<skill-name>" command
    that deterministically reads the skill's SKILL.md and follows it from
    its first step — useful when the user wants a guaranteed, predictable
    step-by-step flow instead of relying on trigger-matching. This only
    covers Claude Code (Cursor has no equivalent commands folder yet).

    AGENTS.md, .gemini/rules/project-rules.md and .github/copilot-instructions.md
    are hand-authored summaries that reference .agents/rules for detail — they
    are intentionally NOT generated by this script (see
    .agents/rules/sync-workflow.md for the reasoning).

    After syncing, the script also checks that every file under .agents/rules,
    .agents/commands and .agents/skills is at least MENTIONED BY NAME in
    docs/proje-haritasi.md, and prints a warning list for anything missing.
    This is a coverage check only — it does not (and cannot) write the
    Turkish description itself, since that requires understanding what the
    new rule/skill/command actually does. Whoever adds the file (human or AI)
    must still write that description by hand in the same turn.

    Finally, it cross-checks the folders this kit ships "empty" (src/,
    examples/, docs/images/) against what the AI-primary files actually
    reference. It does NOT demand all three — a kit may legitimately drop one
    it doesn't use. It flags the two real inconsistencies: a folder that an
    AI-primary file names but that doesn't exist (dead reference), and a folder
    that exists but is empty (git drops empty directories, so it vanishes on
    the next clone). This check exists because that failure was real and
    shipped: examples/ went without a placeholder for months and one kit ended
    up with no examples/ folder at all while three of its own files still
    promised it.

.NOTES
    Run this every time a file under .agents/rules/ or .agents/commands/ is
    added, edited or removed, OR a skill is added/removed under
    .agents/skills/. Safe to re-run — stale generated files (deleted from
    source, or from a removed skill) are removed from targets too.
#>

$ErrorActionPreference = 'Stop'

$RepoRoot       = Split-Path -Parent $PSScriptRoot
$AgentsRules    = Join-Path $RepoRoot ".agents/rules"
$AgentsCommands = Join-Path $RepoRoot ".agents/commands"
$AgentsSkills   = Join-Path $RepoRoot ".agents/skills"

# Per-target extension. Cursor is NOT .md: its rules engine recognizes only
# ".mdc" under .cursor/rules and silently ignores a plain ".md" file there —
# the official docs spell this out with an example ("api-guidelines.md
# # Ignored (wrong extension)", cursor.com/docs/rules). The frontmatter these
# files already carry (description/globs/alwaysApply) is Cursor's own format,
# so the extension was the only thing standing between this kit and Cursor
# actually loading its rules.
$RuleTargets    = @(
    @{ Path = ".claude/rules"; Extension = ".md"  },
    @{ Path = ".cursor/rules"; Extension = ".mdc" }
)
$CommandTargets = @(".claude/commands")
$SkillCommandMarker = "AUTO-GENERATED from .agents/skills"

# Claude Code discovers skills ONLY from .claude/skills/ (plus ~/.claude/skills,
# plugins and enterprise paths) — .agents/skills/ is not a discovery location
# for it. Rather than copying every SKILL.md and creating a second editable
# source, the generator links each skill into place: Claude Code resolves
# symlinks in skill directories and loads a skill reachable from several
# locations only once (code.claude.com/docs/en/skills). .agents/skills/ stays
# the one place anything is ever edited.
$SkillLinkTarget = ".claude/skills"

# Folders this kit ships "empty" — each MUST carry its own README.md, because
# git does not track empty directories. Without that file the folder silently
# disappears from a fresh clone while AGENTS.md / copilot-instructions.md /
# docs/ai-ignore-strategy.md still name it as always-load context, leaving a
# dead reference in the kit. Real, observed failure: examples/ shipped with no
# placeholder for months; one kit ended up with no examples/ folder at all
# while three of its own files still promised it.
$ShipEmptyFolders = @("src", "examples", "docs/images")

function Sync-GeneratedDirectory {
    param(
        [Parameter(Mandatory)] [string]$SourceDir,
        [Parameter(Mandatory)] [string]$TargetRelative,
        [Parameter(Mandatory)] [string]$RepoRoot,
        [string]$IgnoreMarker,
        # Extension the generated copies carry in THIS target. Defaults to the
        # source's own .md; Cursor is the exception — see $RuleTargets below.
        [string]$TargetExtension = ".md"
    )

    $target = Join-Path $RepoRoot $TargetRelative
    if (-not (Test-Path $target)) {
        New-Item -ItemType Directory -Path $target -Force | Out-Null
    }

    $sourceFiles = @(Get-ChildItem -Path $SourceDir -Filter *.md)
    # Match on BaseName, not Name: the target extension may differ from the
    # source's (.md -> .mdc for Cursor), so a Name-based comparison would
    # classify every freshly written file as stale and delete it immediately.
    $sourceBaseNames = @($sourceFiles | Select-Object -ExpandProperty BaseName)

    # Copy first, delete stale second: if the script is interrupted between
    # the two steps, the target is left with stale-but-valid files rather
    # than files removed but not yet replaced.
    $sourceFiles | ForEach-Object {
        $targetName  = "$($_.BaseName)$TargetExtension"
        $destination = Join-Path $target $targetName
        Copy-Item -Path $_.FullName -Destination $destination -Force
        Write-Host "  - synced       : $TargetRelative/$targetName"
    }

    # Sweep every file the generator could own here, not just $TargetExtension —
    # otherwise a target migrating from one extension to another (the .md -> .mdc
    # switch) leaves its old copies behind forever, and Cursor would silently go
    # on reading nothing while two sets of files sit side by side.
    $existingTargetFiles = @(
        Get-ChildItem -Path $target -File -ErrorAction SilentlyContinue |
            Where-Object { $_.Extension -in @(".md", ".mdc") }
    )

    # Safety guard: a source that yields zero files while the target already
    # has content almost always means $SourceDir resolved to the wrong path,
    # not that every rule/command was legitimately deleted. Refuse to mass-
    # delete in that case and surface the problem instead of silently wiping
    # the target.
    if ($sourceBaseNames.Count -eq 0 -and $existingTargetFiles.Count -gt 0) {
        throw "Sync-GeneratedDirectory: source '$SourceDir' yielded 0 .md files but target '$TargetRelative' already has $($existingTargetFiles.Count) — refusing to delete. This usually means the source path is wrong, not that every file was legitimately removed. Verify `$SourceDir before re-running."
    }

    $staleFiles = @($existingTargetFiles | Where-Object {
        # A file is current only if BOTH its name and its extension match what
        # this target is supposed to generate. Same BaseName but the old
        # extension = a leftover from before the migration, and must go.
        if (($sourceBaseNames -contains $_.BaseName) -and ($_.Extension -eq $TargetExtension)) { return $false }
        if ($IgnoreMarker) {
            $fileText = Get-Content -Path $_.FullName -Raw -ErrorAction SilentlyContinue
            if ($fileText -and $fileText.Contains($IgnoreMarker)) { return $false }  # owned by a different generator (e.g. per-skill commands) — leave it alone
        }
        return $true
    })

    if ($staleFiles.Count -gt 0) {
        Write-Host "  - removing $($staleFiles.Count) stale file(s): $($staleFiles.Name -join ', ')"
        $staleFiles | ForEach-Object {
            Remove-Item $_.FullName -Force
            Write-Host "  - removed stale : $TargetRelative/$($_.Name)"
        }
    }
}

Write-Host "Source of truth: .agents/rules, .agents/commands (.agents/skills needs no copying)"
Write-Host ""

Write-Host "Regenerating rules..."
foreach ($t in $RuleTargets) {
    Sync-GeneratedDirectory -SourceDir $AgentsRules -TargetRelative $t.Path -RepoRoot $RepoRoot -TargetExtension $t.Extension
}

Write-Host ""
Write-Host "Regenerating commands..."
foreach ($t in $CommandTargets) {
    Sync-GeneratedDirectory -SourceDir $AgentsCommands -TargetRelative $t -RepoRoot $RepoRoot -IgnoreMarker $SkillCommandMarker
}

Write-Host ""
Write-Host "Regenerating skill commands (.claude/commands/<skill-name>.md, one per .agents/skills/*)..."

$SkillCommandTarget = Join-Path $RepoRoot ".claude/commands"
if (-not (Test-Path $SkillCommandTarget)) {
    New-Item -ItemType Directory -Path $SkillCommandTarget -Force | Out-Null
}

$handAuthoredCommandNames = @()
if (Test-Path $AgentsCommands) {
    $handAuthoredCommandNames = Get-ChildItem -Path $AgentsCommands -Filter *.md | Select-Object -ExpandProperty BaseName
}

$generatedSkillNames = New-Object System.Collections.Generic.List[string]

if (Test-Path $AgentsSkills) {
    Get-ChildItem -Path $AgentsSkills -Directory | ForEach-Object {
        $skillName = $_.Name
        $skillMdPath = Join-Path $_.FullName "SKILL.md"

        if ($handAuthoredCommandNames -contains $skillName) {
            Write-Host "  - SKIPPED (name collides with hand-authored .agents/commands/$skillName.md) : $skillName" -ForegroundColor Yellow
            return
        }
        if (-not (Test-Path $skillMdPath)) {
            Write-Host "  - SKIPPED (no SKILL.md found) : $skillName" -ForegroundColor Yellow
            return
        }

        $content = @"
---
description: Directly invoke the $skillName skill, bypassing natural-language trigger matching.
---

<!-- $SkillCommandMarker/$skillName/SKILL.md — do not hand-edit, regenerate via ``pwsh tools/generate-ai-configs.ps1`` -->

Invoke the ``$skillName`` skill now. Read ``.agents/skills/$skillName/SKILL.md`` in full and follow it exactly from its first step — do not skip or reorder steps, and do not silently infer answers to any question it asks; ask them one at a time, in the order the skill defines.
"@
        $destination = Join-Path $SkillCommandTarget "$skillName.md"
        Set-Content -Path $destination -Value $content -Encoding utf8
        $generatedSkillNames.Add($skillName)
        Write-Host "  - generated    : .claude/commands/$skillName.md"
    }
}

Get-ChildItem -Path $SkillCommandTarget -Filter *.md -ErrorAction SilentlyContinue | ForEach-Object {
    $fileText = Get-Content -Path $_.FullName -Raw -ErrorAction SilentlyContinue
    if ($fileText -and $fileText.Contains($SkillCommandMarker)) {
        if (-not $generatedSkillNames.Contains($_.BaseName)) {
            Remove-Item $_.FullName -Force
            Write-Host "  - removed stale : .claude/commands/$($_.Name)"
        }
    }
}

Write-Host ""
Write-Host "Linking skills into $SkillLinkTarget (one entry per .agents/skills/*)..."

function Remove-LinkOrDirectory {
    param([Parameter(Mandatory)] [string]$Path)

    $item = Get-Item -LiteralPath $Path -Force -ErrorAction SilentlyContinue
    if (-not $item) { return }

    # A junction/symlink must be deleted as a link, never recursed into:
    # Remove-Item -Recurse on a reparse point can follow it and delete the
    # REAL .agents/skills content on the other side. This is the same hazard
    # the .rad hub's own "never rm -rf through a link" discipline exists for.
    if ($item.Attributes -band [System.IO.FileAttributes]::ReparsePoint) {
        [System.IO.Directory]::Delete($item.FullName, $false)
    } else {
        Remove-Item -LiteralPath $item.FullName -Recurse -Force
    }
}

$skillLinkRoot = Join-Path $RepoRoot $SkillLinkTarget
if (-not (Test-Path $skillLinkRoot)) {
    New-Item -ItemType Directory -Path $skillLinkRoot -Force | Out-Null
}

$linkedSkillNames = New-Object System.Collections.Generic.List[string]
$copiedFallback   = New-Object System.Collections.Generic.List[string]

if (Test-Path $AgentsSkills) {
    Get-ChildItem -Path $AgentsSkills -Directory | ForEach-Object {
        $skillName   = $_.Name
        $sourcePath  = $_.FullName
        $linkPath    = Join-Path $skillLinkRoot $skillName
        $linkedSkillNames.Add($skillName)

        $existing = Get-Item -LiteralPath $linkPath -Force -ErrorAction SilentlyContinue
        if ($existing -and ($existing.Attributes -band [System.IO.FileAttributes]::ReparsePoint)) {
            # Already a link — only rebuild it if it points somewhere else.
            $currentTarget = $existing.Target | Select-Object -First 1
            if ($currentTarget -and ((Resolve-Path -LiteralPath $currentTarget -ErrorAction SilentlyContinue).Path -eq $sourcePath)) {
                Write-Host "  - already-ok   : $SkillLinkTarget/$skillName"
                return
            }
        }

        if ($existing) { Remove-LinkOrDirectory -Path $linkPath }

        # Junction first on Windows: unlike a symlink it needs neither elevation
        # nor Developer Mode, so this works on an ordinary developer machine.
        $linkType = if ($IsWindows) { 'Junction' } else { 'SymbolicLink' }
        try {
            New-Item -ItemType $linkType -Path $linkPath -Target $sourcePath -ErrorAction Stop | Out-Null
            Write-Host "  - linked       : $SkillLinkTarget/$skillName -> .agents/skills/$skillName"
        } catch {
            # Last resort on a filesystem that refuses links at all (some network
            # shares, a non-NTFS volume). A copy still makes the skill load; it is
            # reported loudly because it re-introduces the second-editable-source
            # problem this link exists to avoid.
            Copy-Item -Path $sourcePath -Destination $linkPath -Recurse -Force
            $copiedFallback.Add($skillName)
            Write-Host "  - COPIED (link unsupported here) : $SkillLinkTarget/$skillName" -ForegroundColor Yellow
        }
    }
}

Get-ChildItem -Path $skillLinkRoot -Directory -Force -ErrorAction SilentlyContinue | ForEach-Object {
    if (-not $linkedSkillNames.Contains($_.Name)) {
        Remove-LinkOrDirectory -Path $_.FullName
        Write-Host "  - removed stale : $SkillLinkTarget/$($_.Name)"
    }
}

if ($copiedFallback.Count -gt 0) {
    Write-Host ""
    Write-Host "WARNING: $($copiedFallback.Count) skill(s) had to be COPIED instead of linked:" -ForegroundColor Yellow
    $copiedFallback | ForEach-Object { Write-Host "  - $_" -ForegroundColor Yellow }
    Write-Host "Those copies will go stale — .agents/skills/ remains the only file to edit," -ForegroundColor Yellow
    Write-Host "and re-running this script refreshes them." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "Done."

# --- docs/proje-haritasi.md coverage check ------------------------------
$MapFile = Join-Path $RepoRoot "docs/proje-haritasi.md"
if (Test-Path $MapFile) {
    $mapText = Get-Content $MapFile -Raw
    $missing = New-Object System.Collections.Generic.List[string]

    Get-ChildItem -Path $AgentsRules -Filter *.md | ForEach-Object {
        if ($mapText -notmatch [regex]::Escape($_.Name)) {
            $missing.Add(".agents/rules/$($_.Name)")
        }
    }
    Get-ChildItem -Path $AgentsCommands -Filter *.md | ForEach-Object {
        if ($mapText -notmatch [regex]::Escape($_.Name)) {
            $missing.Add(".agents/commands/$($_.Name)")
        }
    }
    $agentsSkills = Join-Path $RepoRoot ".agents/skills"
    if (Test-Path $agentsSkills) {
        Get-ChildItem -Path $agentsSkills -Directory | ForEach-Object {
            if ($mapText -notmatch [regex]::Escape($_.Name)) {
                $missing.Add(".agents/skills/$($_.Name)")
            }
        }
    }

    if ($missing.Count -gt 0) {
        Write-Host ""
        Write-Host "WARNING: docs/proje-haritasi.md does not mention:" -ForegroundColor Yellow
        $missing | ForEach-Object { Write-Host "  - $_" -ForegroundColor Yellow }
        Write-Host "Add a row/description for each before finishing this turn." -ForegroundColor Yellow
    } else {
        Write-Host ""
        Write-Host "docs/proje-haritasi.md coverage: OK (every rule/command/skill is mentioned)."
    }
} else {
    Write-Host ""
    Write-Host "NOTE: docs/proje-haritasi.md not found — skipping coverage check." -ForegroundColor Yellow
}

# --- Ship-empty folder / dead-reference consistency check ---------------------
# The real invariant is NOT "every kit must have all three folders" — a kit
# legitimately drops one it doesn't use (a retrofitted real project has no
# examples/, for instance). The invariant is CONSISTENCY: a folder the kit's own
# AI-primary files point at must actually exist with content, and a folder that
# exists must not be empty (git drops empty directories on the next clone).

$AiPrimaryFiles = @(
    "AGENTS.md",
    ".claude/CLAUDE.md",
    ".github/copilot-instructions.md",
    ".gemini/rules/project-rules.md",
    "docs/ai-ignore-strategy.md"
)

$primaryText = ($AiPrimaryFiles | ForEach-Object {
    $p = Join-Path $RepoRoot $_
    if (Test-Path $p) { Get-Content -Path $p -Raw }
}) -join "`n"

$folderProblems = [System.Collections.Generic.List[string]]::new()

foreach ($rel in $ShipEmptyFolders) {
    $full       = Join-Path $RepoRoot $rel
    $exists     = Test-Path $full
    $entries    = if ($exists) { @(Get-ChildItem -Path $full -Force -ErrorAction SilentlyContinue) } else { @() }
    # Only a GLOB-form reference ("examples/**", "src/**/*.pas") counts as the kit
    # structurally promising the path — that is how the always-load context lists
    # and the ai-ignore tables write it. A bare prose mention ("...saved scripts
    # into `examples/` anyway...") is narrative, not a claim the folder exists,
    # and must not trip this check.
    $referenced = $primaryText -match ([regex]::Escape("$rel/**"))

    if ($referenced -and -not $exists) {
        $folderProblems.Add("$rel/ — DEAD REFERENCE: named in an AI-primary file but the folder does not exist. Create it with a README.md, or drop the reference.")
    }
    elseif ($exists -and $entries.Count -eq 0) {
        $folderProblems.Add("$rel/ — EMPTY: git will drop it on the next clone. Add its README.md placeholder" + $(if ($referenced) { " (an AI-primary file already promises it)." } else { ", or remove the folder." }))
    }
}

if ($folderProblems.Count -gt 0) {
    Write-Host ""
    Write-Host "WARNING: folder/reference mismatch:" -ForegroundColor Yellow
    $folderProblems | ForEach-Object { Write-Host "  - $_" -ForegroundColor Yellow }
    Write-Host "Git does not track empty directories, so an empty folder vanishes on" -ForegroundColor Yellow
    Write-Host "clone while the files naming it as always-load context stay behind." -ForegroundColor Yellow
} else {
    Write-Host "folder/reference consistency: OK ($($ShipEmptyFolders -join ', '))."
}
